# Generated by Django 5.1.5 on 2025-01-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='se_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='st_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='st_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='st_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='t_address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='t_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='passwrord',
            new_name='t_password',
        ),
    ]
