# Generated by Django 5.1.5 on 2025-01-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_semester_se_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='semester',
            name='se_name',
            field=models.CharField(choices=[('EV', 'Everest'), ('AN', 'Annapurna'), ('KA', 'Kanchenjunga'), ('MA', 'Manaslu'), ('LH', 'Lhotse'), ('MK', 'Makalu'), ('DH', 'Dhaulagiri'), ('LA', 'Langtang')], default='EV', max_length=2),
        ),
    ]
