# Generated by Django 5.1.5 on 2025-01-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Lecturer', max_length=100),
        ),
    ]
