# Generated by Django 5.1.5 on 2025-01-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
    ]
