# Generated by Django 5.1.5 on 2025-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_st_exam_roll_no_student_st_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.IntegerField(),
        ),
    ]
