# Generated by Django 5.1.5 on 2025-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='se_name',
            field=models.CharField(choices=[('EV', 'Everest(1st sem)'), ('AN', 'Annapurna(2nd sem)'), ('KA', 'Kanchenjunga(3rd sem)'), ('MA', 'Manaslu(4th sem)'), ('LH', 'Lhotse(5th sem)'), ('MK', 'Makalu(6th sem)'), ('DH', 'Dhaulagiri(7th sem)'), ('LA', 'Langtang(8th sem)')], default='EV', max_length=2),
        ),
    ]
