# Generated by Django 5.1.5 on 2025-01-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_note', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('note_desription', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name_plural': 'Course Notes',
            },
        ),
    ]
