# Generated by Django 5.1.5 on 2025-01-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coursenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursenote',
            old_name='note_desription',
            new_name='note_description',
        ),
    ]
