# Generated by Django 5.1.5 on 2025-02-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_note_desription_coursenote_note_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.DeleteModel(
            name='CourseNote',
        ),
    ]
