# Generated by Django 5.1.5 on 2025-02-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_course_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
    ]
