# Generated by Django 5.1.5 on 2025-02-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Material Type')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon Class')),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Material Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Material File')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Upload Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.course', verbose_name='Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.teacher', verbose_name='Teacher')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.materialtype', verbose_name='Material Type')),
            ],
            options={
                'verbose_name_plural': 'Course Materials',
            },
        ),
    ]
