# Generated by Django 5.1.5 on 2025-02-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_materialtype_coursematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Course Material', 'verbose_name_plural': 'Course Materials'},
        ),
    ]
