# Generated by Django 5.1.5 on 2025-02-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_coursematerial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(choices=[('BOOK', 'Book'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PDF', 'PDF'), ('SLIDES', 'Slides'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], default='PDF', max_length=20, verbose_name='Material Type'),
        ),
    ]
