# Generated by Django 5.1.5 on 2025-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_materialtype_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(choices=[('BOOK', 'Book'), ('DOCX', 'Docx'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PDF', 'PDF'), ('SLIDES', 'Slides'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], default='PDF', max_length=20, verbose_name='Material Type'),
        ),
    ]
