# Generated by Django 5.1.5 on 2025-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_materialtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='se_name',
            field=models.CharField(choices=[('EV', 'Everest (1st sem)'), ('AN', 'Annapurna (2nd sem)'), ('KA', 'Kanchenjunga (3rd sem)'), ('MA', 'Manaslu (4th sem)'), ('LH', 'Lhotse (5th sem)'), ('MK', 'Makalu (6th sem)'), ('DH', 'Dhaulagiri (7th sem)'), ('LA', 'Langtang (8th sem)')], default='EV', max_length=2),
        ),
    ]
