# Generated by Django 5.1.5 on 2025-02-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_coursematerial_is_active_coursematerial_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_password',
            field=models.CharField(default='studentSMC1', max_length=128),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Assignment Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Assignment File')),
                ('deadline', models.DateTimeField(verbose_name='Submission Deadline')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.course', verbose_name='Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-posted_date'],
            },
        ),
    ]
