# Generated by Django 5.1.5 on 2025-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_st_password_alter_teacher_t_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='main.course'),
        ),
    ]
