# Generated by Django 5.1.5 on 2025-02-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
