# Generated by Django 5.1.5 on 2025-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
