# Generated by Django 5.1.5 on 2025-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_course_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='icon_class',
            field=models.CharField(choices=[('BOOK', 'bi-book'), ('DOCX', 'bi-file-earmark-text'), ('VIDEO', 'bi-camera-video'), ('AUDIO', 'bi-music-note'), ('PDF', 'bi-file-earmark-pdf'), ('SLIDES', 'bi-file-earmark-slides'), ('QUIZ', 'bi-question-circle'), ('ASSIGNMENT', 'bi-pencil-square'), ('IMAGE', 'bi-file-image'), ('LINK', 'bi-link'), ('PPTX', 'bi-file-earmark-powerpoint'), ('PPT', 'bi-file-earmark-ppt'), ('XLS', 'bi-file-earmark-excel'), ('XLSX', 'bi-file-earmark-excel'), ('ZIP', 'bi-file-earmark-zip')], default='bi-file-earmark-pdf', max_length=50, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(choices=[('BOOK', 'Book'), ('DOCX', 'Docx'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PDF', 'PDF'), ('SLIDES', 'Slides'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('IMAGE', 'Image'), ('LINK', 'Link'), ('PPTX', 'PPTX'), ('PPT', 'PPT'), ('XLS', 'XLS'), ('XLSX', 'XLSX'), ('ZIP', 'ZIP')], default='PDF', max_length=20, verbose_name='Material Type'),
        ),
    ]
