# Generated by Django 5.1.5 on 2025-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_teacher_gender_teacher_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_image.jpg', null=True, upload_to='teacher_pics/'),
        ),
    ]
