# Generated by Django 5.1.5 on 2025-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='no_image2.jpg', null=True, upload_to='student_pics/'),
        ),
    ]
