# Generated by Django 5.1.5 on 2025-02-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_files/'),
        ),
    ]
