# Generated by Django 5.1.5 on 2025-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile_image.jpg', null=True, upload_to='teacher_pics/'),
        ),
    ]
