# Generated by Django 5.1.5 on 2025-02-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notic_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='Notice File'),
        ),
    ]
