# Generated by Django 5.1.5 on 2025-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_notice_notic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
