# Generated by Django 5.1.5 on 2025-02-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_uploaded_by_result_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='main.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Objective',
                'verbose_name_plural': 'Course Objectives',
            },
        ),
    ]
