# Generated by Django 5.1.5 on 2025-02-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_courseobjectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseobjectives',
            name='objective',
            field=models.CharField(max_length=255),
        ),
    ]
