# Generated by Django 5.1.5 on 2025-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_courseobjectives_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
