# Generated by Django 5.1.5 on 2025-02-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_assignmentsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
