# Generated by Django 5.1.5 on 2025-02-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
