# Generated by Django 5.1.5 on 2025-02-22 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagegroup',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='student_creator',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='students',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='teacher_creator',
        ),
        migrations.RemoveField(
            model_name='news',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='student',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OldQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='old_questions/')),
                ('question_type', models.CharField(choices=[('Objective', 'Objective'), ('Subjective', 'Subjective'), ('Other', 'Other')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
