# Generated by Django 5.1.5 on 2025-02-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='News Image'),
        ),
    ]
