# Generated by Django 5.1.5 on 2025-02-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldquestion',
            name='question_type',
            field=models.CharField(choices=[('Objective', 'Objective'), ('Subjective', 'Subjective')], max_length=20),
        ),
    ]
