# Generated by Django 5.1.5 on 2025-02-22 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_oldquestion_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('feedback_date', models.DateTimeField(auto_now_add=True, verbose_name='Feedback Date')),
                ('assignment_submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.assignmentsubmit')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='main.teacher')),
            ],
            options={
                'verbose_name': 'Assignment Feedback',
                'verbose_name_plural': 'Assignment Feedbacks',
                'ordering': ['-feedback_date'],
            },
        ),
    ]
