# Generated by Django 5.1.5 on 2025-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_assignmentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
