# Generated by Django 5.1.5 on 2025-02-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_assignmentsubmit_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldquestion',
            name='question_leve',
            field=models.CharField(default='Internal', max_length=100, verbose_name='Question Level'),
        ),
    ]
