# Generated by Django 5.1.5 on 2025-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_oldquestion_question_leve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldquestion',
            name='question_leve',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Final', 'Final')], default='Internal', max_length=20),
        ),
    ]
