# Generated by Django 5.1.5 on 2025-02-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_oldquestion_question_leve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldquestion',
            old_name='question_leve',
            new_name='question_level',
        ),
    ]
