# Generated by Django 5.1.5 on 2025-02-26 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_rename_question_leve_oldquestion_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='prescribed_books/')),
                ('book_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_books', to='main.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_books', to='main.semester')),
            ],
            options={
                'verbose_name': 'Prescribed Book',
                'verbose_name_plural': 'Prescribed Books',
            },
        ),
    ]
