# Generated by Django 5.1.5 on 2025-02-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_prescribedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('other', 'Other')], max_length=50)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='main.student')),
            ],
            options={
                'verbose_name': 'Student Social Media',
                'verbose_name_plural': 'Student Social Media',
            },
        ),
    ]
